// Mock data for Kerala engineering colleges and students
export const keralaMemberData = [
  {
    id: "mem1",
    name: "Anu S. Kumar",
    email: "anu.kumar@nitc.ac.in",
    graduationYear: "2024",
    branch: "Computer Science",
    bio: "Passionate about AI/ML and competitive programming.",
    location: "Kozhikode",
    profileColor: "#FF5733",
  },
  {
    id: "mem2",
    name: "Rahul P. Nair",
    email: "rahul.nair@cet.ac.in",
    graduationYear: "2025",
    branch: "Electronics & Communication",
    bio: "Electronics enthusiast, working on IoT projects.",
    location: "Thiruvananthapuram",
    profileColor: "#33FF57",
  },
  {
    id: "mem3",
    name: "Priya V. Menon",
    email: "priya.menon@cusat.ac.in",
    graduationYear: "2023",
    branch: "Civil Engineering",
    bio: "Alumni, interested in sustainable infrastructure.",
    location: "Kochi",
    profileColor: "#3357FF",
  },
  {
    id: "mem4",
    name: "Siddharth R. Pillai",
    email: "siddharth.pillai@gectcr.ac.in",
    graduationYear: "2026",
    branch: "Mechanical Engineering",
    bio: "Aspiring automotive engineer, loves robotics.",
    location: "Thrissur",
    profileColor: "#FF33A1",
  },
  {
    id: "mem5",
    name: "Meera K. Das",
    email: "meera.das@iimk.ac.in",
    graduationYear: "2022",
    branch: "Management",
    bio: "MBA graduate, now a product manager.",
    location: "Kozhikode",
    profileColor: "#A133FF",
  },
  {
    id: "mem6",
    name: "Arjun S. Warrier",
    email: "arjun.warrier@fisat.ac.in",
    graduationYear: "2025",
    branch: "Information Technology",
    bio: "Full-stack developer, open-source contributor.",
    location: "Ernakulam",
    profileColor: "#33FFF0",
  },
  {
    id: "mem7",
    name: "Lakshmi N. Devi",
    email: "lakshmi.devi@mbcet.ac.in",
    graduationYear: "2024",
    branch: "Electrical & Electronics",
    bio: "Renewable energy researcher, loves circuit design.",
    location: "Thiruvananthapuram",
    profileColor: "#FF8C33",
  },
  {
    id: "mem8",
    name: "Gautham M. S.",
    email: "gautham.ms@rajagiri.edu",
    graduationYear: "2026",
    branch: "Computer Science",
    bio: "Learning web development, keen on cybersecurity.",
    location: "Kochi",
    profileColor: "#8C33FF",
  },
  {
    id: "mem9",
    name: "Fathima A. K.",
    email: "fathima.ak@geck.ac.in",
    graduationYear: "2023",
    branch: "Applied Electronics",
    bio: "Alumni, embedded systems engineer.",
    location: "Kozhikode",
    profileColor: "#33FF8C",
  },
  {
    id: "mem10",
    name: "Kevin George",
    email: "kevin.george@gmail.com", // Test user
    graduationYear: "2025",
    branch: "Computer Science",
    bio: "Testing account for Learn.io features.",
    location: "Kochi",
    profileColor: "#FF3333",
  },
]

export const samplePosts = [
  {
    id: 1,
    author: "Anu S. Kumar",
    email: "anu.kumar@nitc.ac.in",
    graduationYear: "2024",
    university: "National Institute of Technology Calicut",
    branch: "Computer Science",
    content:
      "Just finished a challenging competitive programming contest! My team secured 3rd place. So proud of our hard work! #CompetitiveProgramming #NITC #Coding",
    media: null,
    tags: ["CompetitiveProgramming", "NITC", "Coding"],
    timeAgo: "2 hours ago",
    likes: 15,
    comments: 3,
  },
  {
    id: 2,
    author: "Rahul P. Nair",
    email: "rahul.nair@cet.ac.in",
    graduationYear: "2025",
    university: "College of Engineering Trivandrum",
    branch: "Electronics & Communication",
    content:
      "Our IoT smart home project is finally taking shape! The sensor integration was tricky, but we got it working. Any tips for optimizing power consumption? #IoT #SmartHome #Electronics",
    media: {
      type: "image",
      url: "/placeholder.svg?height=300&width=500",
      file: { name: "iot_project.jpg" },
    },
    tags: ["IoT", "SmartHome", "Electronics"],
    timeAgo: "5 hours ago",
    likes: 22,
    comments: 7,
  },
  {
    id: 3,
    author: "Priya V. Menon",
    email: "priya.menon@cusat.ac.in",
    graduationYear: "2023",
    university: "Cochin University of Science and Technology",
    branch: "Civil Engineering",
    content:
      "As an alumni, I'm excited to see the new initiatives for sustainable campus development at CUSAT. Let's build a greener future! #Sustainability #CivilEngineering #CUSAT",
    media: null,
    tags: ["Sustainability", "CivilEngineering", "CUSAT"],
    timeAgo: "1 day ago",
    likes: 10,
    comments: 2,
  },
  {
    id: 4,
    author: "Siddharth R. Pillai",
    email: "siddharth.pillai@gectcr.ac.in",
    graduationYear: "2026",
    university: "Government Engineering College Thrissur",
    branch: "Mechanical Engineering",
    content:
      "First time using a 3D printer for a robotics part! The precision is incredible. Any experienced users have tips for reducing print time? #3DPrinting #Robotics #Mechanical",
    media: {
      type: "image",
      url: "/placeholder.svg?height=300&width=500",
      file: { name: "robot_part.png" },
    },
    tags: ["3DPrinting", "Robotics", "Mechanical"],
    timeAgo: "2 days ago",
    likes: 8,
    comments: 1,
  },
  {
    id: 5,
    author: "Meera K. Das",
    email: "meera.das@iimk.ac.in",
    graduationYear: "2022",
    university: "Indian Institute of Management Kozhikode",
    branch: "Management",
    content:
      "Reflecting on my MBA journey at IIMK. The case study method truly prepares you for real-world business challenges. Highly recommend! #MBA #IIMK #Business",
    media: null,
    tags: ["MBA", "IIMK", "Business"],
    timeAgo: "3 days ago",
    likes: 18,
    comments: 5,
  },
]

export const collegeEvents = [
  {
    id: 1,
    title: "TechFest 2024: Innovation Summit",
    date: "October 26-28, 2024",
    location: "NIT Calicut Auditorium",
    type: "Technical Symposium",
    description:
      "Join us for the annual TechFest, featuring workshops, hackathons, and guest lectures from industry leaders. Don't miss out!",
  },
  {
    id: 2,
    title: "Envision 2024: Entrepreneurship Conclave",
    date: "November 10, 2024",
    location: "CUSAT Seminar Hall",
    type: "Business Event",
    description:
      "A conclave for aspiring entrepreneurs to network, learn from successful startups, and pitch their ideas.",
  },
  {
    id: 3,
    title: "RoboWarz: Inter-College Robotics Competition",
    date: "December 5, 2024",
    location: "CET Trivandrum Robotics Lab",
    type: "Robotics Competition",
    description: "Design, build, and battle your robots against teams from across Kerala!",
  },
]

export const studyGroups = [
  {
    id: 1,
    name: "DSA Enthusiasts (CS/IT)",
    subject: "Data Structures & Algorithms",
    members: 45,
    nextMeeting: "Monday, 7 PM (Online)",
    description: "Weekly problem-solving sessions and discussion on LeetCode problems.",
  },
  {
    id: 2,
    name: "Circuit Breakers (ECE/EEE)",
    subject: "Circuit Design & Analysis",
    members: 30,
    nextMeeting: "Wednesday, 6 PM (Lab 301)",
    description: "Collaborative study for analog and digital circuit courses.",
  },
  {
    id: 3,
    name: "Mech Mavens (ME)",
    subject: "Thermodynamics & Fluid Mechanics",
    members: 20,
    nextMeeting: "Tuesday, 5:30 PM (Library)",
    description: "Group study for core mechanical engineering subjects.",
  },
]
