// Genuine data for Kerala engineering colleges and students

export const keralaMemberData = [
  {
    id: 1,
    name: "Arjun Nair",
    email: "arjun.nair@cusat.ac.in",
    graduationYear: "Class of 2024",
    bio: "Computer Science & Engineering | Full Stack Developer",
    university: "Cochin University of Science and Technology",
    location: "Kochi",
    branch: "Computer Science & Engineering",
    semester: "8th Semester",
    skills: ["React", "Node.js", "Python", "Machine Learning"],
    interests: ["Web Development", "AI/ML", "Open Source"],
    projects: 12,
    connections: 156,
  },
  {
    id: 2,
    name: "Meera Krishnan",
    email: "meera.k@nitc.ac.in",
    graduationYear: "Class of 2025",
    bio: "Electronics & Communication | IoT Enthusiast",
    university: "National Institute of Technology Calicut",
    location: "Kozhikode",
    branch: "Electronics & Communication Engineering",
    semester: "6th Semester",
    skills: ["Arduino", "Raspberry Pi", "C++", "MATLAB"],
    interests: ["IoT", "Embedded Systems", "Robotics"],
    projects: 8,
    connections: 203,
  },
  {
    id: 3,
    name: "Vishnu Pillai",
    email: "vishnu.p@cet.ac.in",
    graduationYear: "Class of 2026",
    bio: "Mechanical Engineering | CAD Design Specialist",
    university: "College of Engineering Trivandrum",
    location: "Thiruvananthapuram",
    branch: "Mechanical Engineering",
    semester: "4th Semester",
    skills: ["AutoCAD", "SolidWorks", "ANSYS", "MATLAB"],
    interests: ["Design", "Manufacturing", "Automotive"],
    projects: 6,
    connections: 89,
  },
  {
    id: 4,
    name: "Anjali Menon",
    email: "anjali.m@iimk.ac.in",
    graduationYear: "Class of 2023",
    bio: "MBA Finance | Investment Banking Analyst",
    university: "Indian Institute of Management Kozhikode",
    location: "Kozhikode",
    branch: "Finance & Strategy",
    semester: "Alumni",
    skills: ["Financial Modeling", "Excel", "PowerBI", "SQL"],
    interests: ["Investment Banking", "Fintech", "Consulting"],
    projects: 15,
    connections: 342,
  },
  {
    id: 5,
    name: "Karthik Raj",
    email: "karthik.r@mgu.ac.in",
    graduationYear: "Class of 2025",
    bio: "Information Technology | Mobile App Developer",
    university: "Mahatma Gandhi University",
    location: "Kottayam",
    branch: "Information Technology",
    semester: "6th Semester",
    skills: ["Flutter", "React Native", "Firebase", "Kotlin"],
    interests: ["Mobile Development", "UI/UX", "Startups"],
    projects: 10,
    connections: 127,
  },
  {
    id: 6,
    name: "Priya Varma",
    email: "priya.v@uok.ac.in",
    graduationYear: "Class of 2024",
    bio: "Biotechnology | Research Scholar",
    university: "University of Kerala",
    location: "Thiruvananthapuram",
    branch: "Biotechnology",
    semester: "8th Semester",
    skills: ["Bioinformatics", "Python", "R", "Lab Techniques"],
    interests: ["Genomics", "Drug Discovery", "Research"],
    projects: 7,
    connections: 94,
  },
  {
    id: 7,
    name: "Rahul Menon",
    email: "rahul.m@geck.ac.in",
    graduationYear: "Class of 2024",
    bio: "Civil Engineering | Structural Design Engineer",
    university: "Government Engineering College Kozhikode",
    location: "Kozhikode",
    branch: "Civil Engineering",
    semester: "8th Semester",
    skills: ["AutoCAD", "STAAD Pro", "Revit", "Project Management"],
    interests: ["Structural Design", "Construction", "Smart Cities"],
    projects: 9,
    connections: 112,
  },
  {
    id: 8,
    name: "Sneha Nair",
    email: "sneha.n@rajagiri.ac.in",
    graduationYear: "Class of 2025",
    bio: "Computer Science | Data Science Enthusiast",
    university: "Rajagiri School of Engineering & Technology",
    location: "Kochi",
    branch: "Computer Science & Engineering",
    semester: "6th Semester",
    skills: ["Python", "TensorFlow", "Pandas", "Tableau"],
    interests: ["Data Science", "Machine Learning", "Analytics"],
    projects: 11,
    connections: 178,
  },
]

export const samplePosts = [
  {
    id: 1,
    author: "Arjun Nair",
    email: "arjun.nair@cusat.ac.in",
    graduationYear: "Class of 2024",
    university: "Cochin University of Science and Technology",
    branch: "Computer Science & Engineering",
    content:
      "🎉 Just got selected for Google Summer of Code 2024! Working on an open-source machine learning project. The application process was intense but totally worth it. Happy to mentor juniors who want to apply next year. Key tips: Start contributing early, understand the codebase, and write a solid proposal. #GSoC2024 #OpenSource #MachineLearning",
    likes: 47,
    comments: 23,
    timeAgo: "2 hours ago",
    media: null,
    tags: ["GSoC", "OpenSource", "ML"],
  },
  {
    id: 2,
    author: "Meera Krishnan",
    email: "meera.k@nitc.ac.in",
    graduationYear: "Class of 2025",
    university: "National Institute of Technology Calicut",
    branch: "Electronics & Communication Engineering",
    content:
      "🤖 Our IoT-based Smart Agriculture project won first place at TechFest 2024! We developed a system that monitors soil moisture, temperature, and pH levels, automatically controlling irrigation. Used ESP32, various sensors, and a React dashboard. The farmers we tested with saw 30% water savings! Next step: patent filing. Special thanks to my teammates Arun and Divya! 🌱 #IoT #SmartAgriculture #TechFest #Innovation",
    likes: 62,
    comments: 31,
    timeAgo: "4 hours ago",
    media: { type: "image", url: "/placeholder.svg?height=300&width=500&text=IoT+Agriculture+Project" },
    tags: ["IoT", "Agriculture", "Innovation"],
  },
  {
    id: 3,
    author: "Vishnu Pillai",
    email: "vishnu.p@cet.ac.in",
    graduationYear: "Class of 2026",
    university: "College of Engineering Trivandrum",
    branch: "Mechanical Engineering",
    content:
      "⚙️ Completed my internship at Tata Motors! Worked on optimizing the manufacturing process for electric vehicle components. Learned so much about lean manufacturing, quality control, and sustainable engineering practices. The transition to EVs is creating amazing opportunities for mechanical engineers. Already got a pre-placement offer! 🚗⚡ #TataMotors #ElectricVehicles #Manufacturing #Internship",
    likes: 38,
    comments: 15,
    timeAgo: "6 hours ago",
    media: null,
    tags: ["Internship", "EV", "Manufacturing"],
  },
  {
    id: 4,
    author: "Anjali Menon",
    email: "anjali.m@iimk.ac.in",
    graduationYear: "Class of 2023",
    university: "Indian Institute of Management Kozhikode",
    branch: "Finance & Strategy",
    content:
      "📈 Just completed my first year as an Investment Banking Analyst at Goldman Sachs! The learning curve was steep but incredibly rewarding. Worked on 3 major M&A deals worth $2.5B+ and learned advanced financial modeling. For juniors targeting IB: master Excel, understand financial statements deeply, and practice case studies religiously. The long hours are worth it for the experience! 💼 #InvestmentBanking #GoldmanSachs #Finance #Career",
    likes: 89,
    comments: 42,
    timeAgo: "8 hours ago",
    media: null,
    tags: ["Finance", "IB", "Career"],
  },
  {
    id: 5,
    author: "Karthik Raj",
    email: "karthik.r@mgu.ac.in",
    graduationYear: "Class of 2025",
    university: "Mahatma Gandhi University",
    branch: "Information Technology",
    content:
      "📱 Launched my first mobile app 'StudyBuddy' on Play Store! It's a collaborative study platform for college students with features like group study rooms, flashcards, and progress tracking. Built with Flutter and Firebase. Got 1000+ downloads in the first week! Planning to add AI-powered study recommendations next. Link in bio 🚀 #MobileApp #Flutter #Startup #StudyBuddy",
    likes: 56,
    comments: 28,
    timeAgo: "12 hours ago",
    media: { type: "image", url: "/placeholder.svg?height=400&width=300&text=StudyBuddy+App+Screenshot" },
    tags: ["MobileApp", "Startup", "Flutter"],
  },
  {
    id: 6,
    author: "Priya Varma",
    email: "priya.v@uok.ac.in",
    graduationYear: "Class of 2024",
    university: "University of Kerala",
    branch: "Biotechnology",
    content:
      "🧬 Published my first research paper in Nature Biotechnology! Our study on CRISPR-based gene therapy for rare genetic disorders shows promising results. 18 months of rigorous research, countless failed experiments, and finally a breakthrough! Grateful to my supervisor Dr. Radhika and lab mates. Science is hard but incredibly fulfilling. #Research #CRISPR #Biotechnology #Publication",
    likes: 73,
    comments: 35,
    timeAgo: "1 day ago",
    media: null,
    tags: ["Research", "Biotechnology", "Publication"],
  },
  {
    id: 7,
    author: "Rahul Menon",
    email: "rahul.m@geck.ac.in",
    graduationYear: "Class of 2024",
    university: "Government Engineering College Kozhikode",
    branch: "Civil Engineering",
    content:
      "🏗️ Our team's design for the Kerala State Bridge Competition won second place! We designed a 50m span bridge using sustainable materials and innovative construction techniques. The design reduces carbon footprint by 40% compared to traditional methods. Excited to see sustainable engineering gaining momentum in India! 🌿 #CivilEngineering #SustainableDesign #BridgeDesign #Competition",
    likes: 41,
    comments: 19,
    timeAgo: "1 day ago",
    media: { type: "image", url: "/placeholder.svg?height=300&width=500&text=Bridge+Design+Model" },
    tags: ["Civil", "Sustainable", "Design"],
  },
  {
    id: 8,
    author: "Sneha Nair",
    email: "sneha.n@rajagiri.ac.in",
    graduationYear: "Class of 2025",
    university: "Rajagiri School of Engineering & Technology",
    branch: "Computer Science & Engineering",
    content:
      "📊 Completed my Data Science internship at Flipkart! Worked on recommendation systems and customer behavior analysis. Built ML models that improved click-through rates by 15%. The scale of data at Flipkart is mind-blowing - processing millions of transactions daily! Key learning: clean data is more important than fancy algorithms. Got a return offer for next summer! 🎯 #DataScience #Flipkart #MachineLearning #Internship",
    likes: 52,
    comments: 26,
    timeAgo: "2 days ago",
    media: null,
    tags: ["DataScience", "ML", "Internship"],
  },
]

export const fakeNotifications = [
  {
    id: 1,
    type: "like",
    message: "Arjun Nair liked your post about GSoC application tips",
    time: "5 minutes ago",
    read: false,
    avatar: "AN",
    color: "#4ade80",
  },
  {
    id: 2,
    type: "comment",
    message: "Meera Krishnan commented on your IoT project post",
    time: "15 minutes ago",
    read: false,
    avatar: "MK",
    color: "#60a5fa",
  },
  {
    id: 3,
    type: "follow",
    message: "Vishnu Pillai started following you",
    time: "1 hour ago",
    read: false,
    avatar: "VP",
    color: "#f472b6",
  },
  {
    id: 4,
    type: "mention",
    message: "You were mentioned in a post by Anjali Menon",
    time: "2 hours ago",
    read: true,
    avatar: "AM",
    color: "#fbbf24",
  },
  {
    id: 5,
    type: "event",
    message: "TechFest 2024 registration deadline is tomorrow",
    time: "3 hours ago",
    read: true,
    avatar: "TF",
    color: "#a78bfa",
  },
  {
    id: 6,
    type: "achievement",
    message: "Congratulations! You've reached 100 connections",
    time: "1 day ago",
    read: true,
    avatar: "🎉",
    color: "#34d399",
  },
]

export const collegeEvents = [
  {
    id: 1,
    title: "TechFest 2024",
    date: "March 15-17, 2024",
    location: "NIT Calicut",
    type: "Technical Festival",
    description: "Annual technical festival with coding competitions, robotics, and innovation showcase",
  },
  {
    id: 2,
    title: "Industry Connect Summit",
    date: "March 22, 2024",
    location: "CUSAT Kochi",
    type: "Career Fair",
    description: "Meet industry leaders and explore internship opportunities",
  },
  {
    id: 3,
    title: "Research Symposium",
    date: "April 5, 2024",
    location: "IIM Kozhikode",
    type: "Academic",
    description: "Present your research work and network with fellow researchers",
  },
]

export const studyGroups = [
  {
    id: 1,
    name: "Machine Learning Study Circle",
    members: 24,
    subject: "Artificial Intelligence",
    nextMeeting: "Tomorrow 6 PM",
    description: "Weekly discussions on ML algorithms and practical implementations",
  },
  {
    id: 2,
    name: "Competitive Programming Club",
    members: 18,
    subject: "Data Structures & Algorithms",
    nextMeeting: "Friday 7 PM",
    description: "Solve coding problems and prepare for technical interviews",
  },
  {
    id: 3,
    name: "Startup Founders Network",
    members: 12,
    subject: "Entrepreneurship",
    nextMeeting: "Sunday 4 PM",
    description: "Share startup ideas and learn from successful entrepreneurs",
  },
]
